### ISSUE TITLE
The following error occurred while running centos

### ISSUE THREAD

**Issue by tmcyfy** [redfast00/dmr-brandmeister#1]
2021/03/01 23:20:08 starting listening loop
Decoding AMBE stdin to 8kHz Raw Mono Signed stdout.
2021/03/01 23:20:08 got challenge
2021/03/01 23:20:08 sending challenge response
2021/03/01 23:20:08 sending subscription
2021/03/01 23:20:08 got subscription ack
2021/03/01 23:20:08 logged in
2021/03/01 23:20:28 Got unrecognised:  2343
2021/03/01 23:20:28 Got unrecognised:  2343
2021/03/01 23:20:28 Got unrecognised:  2343
2021/03/01 23:20:28 Got unrecognised:  2321
2021/03/01 23:20:28 Got unrecognised:  2321
2021/03/01 23:20:28 Got unrecognised:  2321
2021/03/01 23:20:28 got dmr audio frame
2021/03/01 23:20:28 b9e881526173002a6bb9e881526173002a6bb9e881526173002a6b
Traceback (most recent call last):
  File "to_ambe_format_file.py", line 10, in <module>
    stdout.write(bytes.fromhex(line))
ValueError: non-hexadecimal number found in fromhex() arg at position 14
Done with AMBE test.
2021/03/01 23:20:28 got dmr audio frame
2021/03/01 23:20:28 b9e881526173002a6bb9e881526173002a6bb9e881526173002a6b
Traceback (most recent call last):
  File "decode72to49.py", line 237, in <module>
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
2021/03/01 23:20:28 got dmr audio frame
2021/03/01 23:20:28 b9e881526173002a6bb9e881526173002a6b954be6500310b00777

**Comment by redfast00** [comment]
I'm afraid I can't reproduce this issue. Can you add a `try/except` and a print-statement around the code in `to_ambe_format_file.py` and see what `line` is when it fails? Do you have this issue with a specific group? Does this happen every time?

I understand that the OpenDMR version of this software is easier to get credentials for, but maybe you can try using [the SEA version](https://github.com/redfast00/brandmeister-dmr-sea) which is a lot easier to set up (just a Docker container).

**Comment by tmcyfy** [comment]
OK, I'll try again. Thanks

**Comment by redfast00** [comment]
I'll reopen the issue since we don't know what the problem is yet

**Comment by redfast00** [comment]
@tmcyfy did you get it to work?

**Comment by tmcyfy** [comment]
Sorry, because of work, I haven't tried again.
Especially I am not very familiar with Pyhton, so I don't know how to add print.
Later, I will learn how to add print statement.
